name: Run unit tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go 1.21
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    - name: Run unit tests
      run: |
        go test -v ./ -run TestExecuteReq